CREATE TABLE CAR(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(40) NOT NULL,
    model VARCHAR(40) NOT NULL,
    loanIdentifier BIGINT AUTO_INCREMENT
);

CREATE TABLE CLIENT(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    rentedCar BIGINT
);

ALTER TABLE CLIENT ADD CONSTRAINT rentedCar_loanIdentifier FOREIGN KEY (rentedCar) REFERENCES CAR(loanIdentifier);