CREATE TABLE CAR(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(40) NOT NULL,
    model VARCHAR(40) NOT NULL,
    loan_identifier BIGINT AUTO_INCREMENT
);

CREATE TABLE CLIENT(
    client_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    rented_car BIGINT
);

ALTER TABLE CLIENT
    ADD CONSTRAINT rentedCar_loanIdentifier
    FOREIGN KEY (rented_car) REFERENCES CAR(loan_identifier);